/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

///** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
//const sidebars = {
// By default, Docusaurus generates a sidebar from the docs folder structure
//  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

// But you can create a sidebar manually
/*
tutorialSidebar: [
  {
    type: 'category',
    label: 'Tutorial',
    items: ['hello'],
  },
],
 */
//};

//module.exports = sidebars;

module.exports = {
  /*mySidebar: [
    {
      type: 'category',
      label: 'Started',
      items: [
        {
          type: 'doc',
          id: 'greeting',
        },
      ],
    },
    {
      type: 'category',
      label: 'Intro',
      items: [
        {
          type: 'doc',
          id: 'guide/hello',
        },
        {
          type: 'doc',
          id: 'intro',
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'category',
      label: 'First chapter',
      items: [
        {
          type: 'doc',
          id: 'guide/hello',
        },
        {
          type: 'doc',
          id: 'guide/son_folder/son_guide',
        },
      ],
    },
  ],*/
  /*docs:[
    {
      type: 'doc',
      id: 'greeting',
      label: "Getting started",
    },
    'guide/son_folder/son_guide',
    {
      type: 'link',
      label: 'Baidu',
      href: 'http://www.baidu.com',
    },
  ],*/
  /*myHtmlSidebar: [
    {
      type: 'html',
      value: 'core meaning',
      className: 'sidebar-title',
    },
  ],*/
    docs: [
      {
        type: 'category',
        label: 'Guides',
        collapsible: true,
        collapsed: false,
        items: [
          'JAKA',
        ],
      },
    ],

    // docs: [
    //   {
    //     type: 'autogenerated',
    //     dirName: '.',
    //   },
    //   {
    //     'Getting started': ['greeting'],
    //     Docusaurus: ['guide/hello','guide/son_folder/son_guide'],
    //   },
    //   {
    //     type: 'category',
    //     label: 'Guides',
    //     link: {
    //       type: 'generated-index',
    //       title: 'Docusaurus Guides',
    //       description: 'Learn about the most important Docusaurus concepts!',
    //       slug: 'helloMarkdown',
    //       keywords: ['guides'],
    //       image: 'docusaurus.png',
    //     },
    //     items: ['greeting', 'intro', 'guide/son_folder/son_guide'],
    //   },
    //   {
    //     type: 'category',
    //     label: 'Getting Start',
    //     items: [
    //       'greeting',
    //     ],
    //   },
    //   {
    //     type: 'category',
    //     label: 'Docusaurus',
    //     items: [
    //       'guide/hello',
    //       'guide/son_folder/son_guide',
    //     ],
    //   },
    //   {
    //     type: 'link',
    //     label: 'Learn more',
    //     href: 'http://www.baidu.com',
    //   },
    //   {
    //     type: 'link',
    //     label: 'Learn more and more',
    //     href: 'http://www.baidu.com',
    //   },
    // ],
    
    /*sidebar: [
      {
        'Getting started' : ['guide/hello','guide/son_folder/son_guide',],
      },
    ],*/
  /*  docs: [
      {
        'Getting started': ['greeting'],
        Docusaurus: ['guide/hello','guide/son_folder/son_guide'],

      },
      {
        type: 'link',
        label: 'Learn more',
        href: 'http://www.baidu.com',
      },
      {
        type: 'link',
        label: 'Learn more and more',
        href: 'http://www.baidu.com',
      },
    ],*/
};
